/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminGUI;

import code.HospitalDirectory;
import gui.doctorRecords;
import gui.encounterRecords;
import gui.hospitalRecord;
import gui.patientRecords;
import AdminGUI.ManagePersons;
import code.PersonDirectory;
import code.PatientDirectory;
import gui.vitalSignsRecord;


/**
 *
 * @author Rajvi
 */
public class adminPortal extends javax.swing.JFrame {
    HospitalDirectory hospitalDirectory;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    /**
     * Creates new form adminPortal
     */
    public adminPortal() {
        
        initComponents();
        hospitalDirectory=new HospitalDirectory();
        personDirectory= new PersonDirectory();
        patientDirectory= new PatientDirectory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminSplitPane = new javax.swing.JSplitPane();
        adminRightPane = new javax.swing.JPanel();
        adminLeftPane = new javax.swing.JPanel();
        adminEncounterButton = new javax.swing.JButton();
        managePersonButton = new javax.swing.JButton();
        adminPatientButton = new javax.swing.JButton();
        adminDoctorButton = new javax.swing.JButton();
        adminHospitalButton = new javax.swing.JButton();
        manageVitalSignsButton = new javax.swing.JButton();
        manageDoctorsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminSplitPane.setBackground(new java.awt.Color(255, 255, 255));
        adminSplitPane.setDividerLocation(450);
        adminSplitPane.setPreferredSize(new java.awt.Dimension(250, 100
        ));

        adminRightPane.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout adminRightPaneLayout = new javax.swing.GroupLayout(adminRightPane);
        adminRightPane.setLayout(adminRightPaneLayout);
        adminRightPaneLayout.setHorizontalGroup(
            adminRightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        adminRightPaneLayout.setVerticalGroup(
            adminRightPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );

        adminSplitPane.setRightComponent(adminRightPane);

        adminLeftPane.setBackground(new java.awt.Color(204, 255, 204));

        adminEncounterButton.setText("Encounter Records");
        adminEncounterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEncounterButtonActionPerformed(evt);
            }
        });

        managePersonButton.setText("Manage Persons");
        managePersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonButtonActionPerformed(evt);
            }
        });

        adminPatientButton.setText("Manage Patients");
        adminPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPatientButtonActionPerformed(evt);
            }
        });

        adminDoctorButton.setText("Doctor Records");
        adminDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDoctorButtonActionPerformed(evt);
            }
        });

        adminHospitalButton.setText("Hospital Records");
        adminHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminHospitalButtonActionPerformed(evt);
            }
        });

        manageVitalSignsButton.setText("Manage Vital Signs");
        manageVitalSignsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVitalSignsButtonActionPerformed(evt);
            }
        });

        manageDoctorsButton.setText("Manage Doctors");

        javax.swing.GroupLayout adminLeftPaneLayout = new javax.swing.GroupLayout(adminLeftPane);
        adminLeftPane.setLayout(adminLeftPaneLayout);
        adminLeftPaneLayout.setHorizontalGroup(
            adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLeftPaneLayout.createSequentialGroup()
                .addGroup(adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLeftPaneLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminHospitalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminEncounterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminLeftPaneLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageVitalSignsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(managePersonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminPatientButton)
                            .addComponent(manageDoctorsButton))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        adminLeftPaneLayout.setVerticalGroup(
            adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLeftPaneLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(adminDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(adminHospitalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminEncounterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addGroup(adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminLeftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageVitalSignsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(manageDoctorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        adminSplitPane.setLeftComponent(adminLeftPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminEncounterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEncounterButtonActionPerformed
        // TODO add your handling code here:
         encounterRecords viewEncounter = new encounterRecords();
         adminSplitPane.setRightComponent(viewEncounter);
        
    }//GEN-LAST:event_adminEncounterButtonActionPerformed

    private void managePersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonButtonActionPerformed
        // TODO add your handling code here:
        ManagePersons createPanel = new ManagePersons(adminSplitPane,personDirectory);
        adminSplitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_managePersonButtonActionPerformed

    private void adminPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPatientButtonActionPerformed
        // TODO add your handling code here:
       /* managePatients createPanel = new managePatients(adminSplitPane,personDirectory,patientDirectory);
        adminSplitPane.setRightComponent(createPanel);*/
       patientRecords createPanel = new patientRecords(adminSplitPane,personDirectory,patientDirectory);
       adminSplitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_adminPatientButtonActionPerformed

    private void adminDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDoctorButtonActionPerformed
        // TODO add your handl         adminSplitPane.setRightComponent(viewDoctor);ing code here:patientRecords createPanel = new patientRecords();
        doctorRecords viewDoctor = new doctorRecords();
         adminSplitPane.setRightComponent(viewDoctor);
    }//GEN-LAST:event_adminDoctorButtonActionPerformed

    private void adminHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminHospitalButtonActionPerformed
        // TODO add your handling code here:
        hospitalRecord viewHospital = new hospitalRecord(adminSplitPane,hospitalDirectory);
        adminSplitPane.setRightComponent(viewHospital);
    }//GEN-LAST:event_adminHospitalButtonActionPerformed

    private void manageVitalSignsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVitalSignsButtonActionPerformed
        // TODO add your handling code here:
        vitalSignsRecord createPanel = new vitalSignsRecord(adminSplitPane,personDirectory,patientDirectory);
       adminSplitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_manageVitalSignsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminDoctorButton;
    private javax.swing.JButton adminEncounterButton;
    private javax.swing.JButton adminHospitalButton;
    private javax.swing.JPanel adminLeftPane;
    private javax.swing.JButton adminPatientButton;
    private javax.swing.JPanel adminRightPane;
    private javax.swing.JSplitPane adminSplitPane;
    private javax.swing.JButton manageDoctorsButton;
    private javax.swing.JButton managePersonButton;
    private javax.swing.JButton manageVitalSignsButton;
    // End of variables declaration//GEN-END:variables
 

}

