/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Model.Employee;
import Model.EmployeeHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naman
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    EmployeeHistory history;
    
    public ViewJPanel(EmployeeHistory history) {
        initComponents();
        this.history = history;
        fillTable();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewJPanelTable = new javax.swing.JTable();
        ViewJPanelView = new javax.swing.JButton();
        ViewJPanelDelete = new javax.swing.JButton();
        ViewJPanelContactNumber = new javax.swing.JLabel();
        ViewJPanelLevel = new javax.swing.JLabel();
        ViewJPanelPositionTitle = new javax.swing.JLabel();
        ViewJPanelEmailID = new javax.swing.JLabel();
        ViewJPanelGender = new javax.swing.JLabel();
        ViewJPanelTeamInfo = new javax.swing.JLabel();
        ViewJPanelEmployeeID = new javax.swing.JLabel();
        ViewJPanelName = new javax.swing.JLabel();
        ViewJPanelAge = new javax.swing.JLabel();
        ViewJPanelStartDate = new javax.swing.JLabel();
        ViewJPanelTextFieldAge = new javax.swing.JTextField();
        ViewJPanelTextFieldName = new javax.swing.JTextField();
        ViewJPanelTextFieldEmployeeID = new javax.swing.JTextField();
        ViewJPanelTextFieldGender = new javax.swing.JTextField();
        ViewJPanelTextFieldStartDate = new javax.swing.JTextField();
        ViewJPanelTextFieldEmailID = new javax.swing.JTextField();
        ViewJPanelTextFieldTeamInfo = new javax.swing.JTextField();
        ViewJPanelTextFieldContactNumber = new javax.swing.JTextField();
        ViewJPanelTextFieldPositionTitle = new javax.swing.JTextField();
        ViewJPanelTextFieldLevel = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Employee Details");

        ViewJPanelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Contact Number", "Email ID", "Level", "Position Title", "Team Information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ViewJPanelTable);

        ViewJPanelView.setText("View");
        ViewJPanelView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJPanelViewActionPerformed(evt);
            }
        });

        ViewJPanelDelete.setText("Delete");
        ViewJPanelDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJPanelDeleteActionPerformed(evt);
            }
        });

        ViewJPanelContactNumber.setText("Contact Number");

        ViewJPanelLevel.setText("Level");

        ViewJPanelPositionTitle.setText("Position Title");

        ViewJPanelEmailID.setText("Email ID");

        ViewJPanelGender.setText("Gender");

        ViewJPanelTeamInfo.setText("Team Info");

        ViewJPanelEmployeeID.setText("Employee ID");

        ViewJPanelName.setText("Name");

        ViewJPanelAge.setText("Age");

        ViewJPanelStartDate.setText("Start Date");

        ViewJPanelTextFieldEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJPanelTextFieldEmailIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(ViewJPanelView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewJPanelDelete)
                        .addContainerGap(516, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewJPanelName)
                    .addComponent(ViewJPanelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewJPanelEmployeeID)
                    .addComponent(ViewJPanelGender)
                    .addComponent(ViewJPanelStartDate))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ViewJPanelTextFieldStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(ViewJPanelTextFieldGender, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewJPanelTextFieldAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewJPanelTextFieldEmployeeID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewJPanelTextFieldName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewJPanelLevel)
                            .addComponent(ViewJPanelPositionTitle)
                            .addComponent(ViewJPanelTeamInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewJPanelTextFieldPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewJPanelTextFieldTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewJPanelTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ViewJPanelEmailID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewJPanelTextFieldEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewJPanelContactNumber)
                        .addGap(18, 18, 18)
                        .addComponent(ViewJPanelTextFieldContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewJPanelContactNumber)
                            .addComponent(ViewJPanelTextFieldContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewJPanelTextFieldEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewJPanelEmailID))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewJPanelTextFieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewJPanelLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewJPanelTextFieldPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewJPanelPositionTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewJPanelView)
                            .addComponent(ViewJPanelDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ViewJPanelName)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ViewJPanelTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ViewJPanelTextFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewJPanelEmployeeID))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ViewJPanelTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewJPanelAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ViewJPanelGender))
                            .addComponent(ViewJPanelTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ViewJPanelTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewJPanelStartDate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ViewJPanelTextFieldTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewJPanelTeamInfo)))
                .addGap(132, 132, 132))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewJPanelTextFieldEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJPanelTextFieldEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewJPanelTextFieldEmailIDActionPerformed

    private void ViewJPanelDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJPanelDeleteActionPerformed
       int selectedRowIndex = ViewJPanelTable.getSelectedRow();
      
       if(selectedRowIndex<0)
       {
         JOptionPane.showMessageDialog(this, "Please select a row to delete.");
         return;
       }
        DefaultTableModel model = (DefaultTableModel) ViewJPanelTable.getModel();
        Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteEmployee(selectedEmployee);
        JOptionPane.showMessageDialog(this, "Employee information deleted.");
        fillTable();
       
// TODO add your handling code here:
    }//GEN-LAST:event_ViewJPanelDeleteActionPerformed

    private void ViewJPanelViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJPanelViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = ViewJPanelTable.getSelectedRow();
      
       if(selectedRowIndex<0)
       {
         JOptionPane.showMessageDialog(this, "Please select a row to delete.");
         return;
       }
        DefaultTableModel model = (DefaultTableModel) ViewJPanelTable.getModel();
        Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex, 0);
        ViewJPanelTextFieldName.setText(selectedEmployee.getEmpName());
        ViewJPanelTextFieldContactNumber.setText(selectedEmployee.getEmpContactNumber());
        ViewJPanelTextFieldEmailID.setText(selectedEmployee.getEmpEmail());
        ViewJPanelTextFieldGender.setText(selectedEmployee.getEmpGender());
        ViewJPanelTextFieldLevel.setText(selectedEmployee.getEmpLevel());
        ViewJPanelTextFieldPositionTitle.setText(selectedEmployee.getEmpPositionTitle());
        ViewJPanelTextFieldStartDate.setText(selectedEmployee.getEmpStartDate());
        ViewJPanelTextFieldTeamInfo.setText(selectedEmployee.getEmpTeamInfo());
        ViewJPanelTextFieldAge.setText(String.valueOf(selectedEmployee.getEmpAge()));
        ViewJPanelTextFieldEmployeeID.setText(String.valueOf(selectedEmployee.getEmpId()));
        
        
 
    }//GEN-LAST:event_ViewJPanelViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewJPanelAge;
    private javax.swing.JLabel ViewJPanelContactNumber;
    private javax.swing.JButton ViewJPanelDelete;
    private javax.swing.JLabel ViewJPanelEmailID;
    private javax.swing.JLabel ViewJPanelEmployeeID;
    private javax.swing.JLabel ViewJPanelGender;
    private javax.swing.JLabel ViewJPanelLevel;
    private javax.swing.JLabel ViewJPanelName;
    private javax.swing.JLabel ViewJPanelPositionTitle;
    private javax.swing.JLabel ViewJPanelStartDate;
    private javax.swing.JTable ViewJPanelTable;
    private javax.swing.JLabel ViewJPanelTeamInfo;
    private javax.swing.JTextField ViewJPanelTextFieldAge;
    private javax.swing.JTextField ViewJPanelTextFieldContactNumber;
    private javax.swing.JTextField ViewJPanelTextFieldEmailID;
    private javax.swing.JTextField ViewJPanelTextFieldEmployeeID;
    private javax.swing.JTextField ViewJPanelTextFieldGender;
    private javax.swing.JTextField ViewJPanelTextFieldLevel;
    private javax.swing.JTextField ViewJPanelTextFieldName;
    private javax.swing.JTextField ViewJPanelTextFieldPositionTitle;
    private javax.swing.JTextField ViewJPanelTextFieldStartDate;
    private javax.swing.JTextField ViewJPanelTextFieldTeamInfo;
    private javax.swing.JButton ViewJPanelView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) ViewJPanelTable.getModel();
        model.setRowCount(0);
        
        for (Employee vs : history.getHistory())
        {
          Object[] row = new Object[10];
          row[0] = vs;
          row[1] = vs.getEmpId();
          row[2] = vs.getEmpAge();
          row[3] = vs.getEmpGender();
          row[4] = vs.getEmpStartDate();
          row[5] = vs.getEmpContactNumber();
          row[6] = vs.getEmpId();
          row[7] = vs.getEmpLevel();
          row[8] = vs.getEmpPositionTitle();
          row[9] = vs.getEmpTeamInfo();
          
          model.addRow(row);
          
          
          
        }
    }
    
}

