/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import code.MyNumericVerifier;
import code.Patient;
import code.PatientDirectory;
import code.PersonDirectory;
import code.VitalSign;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author Rajvi
 * 
 */

public class createVitalSigns extends javax.swing.JPanel {
    JSplitPane sp;
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    Patient patient;
    /**
     * Creates new form createVitalSigns
     */
    public createVitalSigns(JSplitPane sp,PersonDirectory personDirectory, PatientDirectory patientDirectory, Patient patient) {
        initComponents();
        this.patient=patient;
        this.sp=sp;
        this.patientDirectory=patientDirectory;
        this.personDirectory=personDirectory;
        addVerifiers();
    }
    private void addVerifiers() {
        InputVerifier integerVerifier = new MyNumericVerifier();
        respiratoryText.setInputVerifier(integerVerifier);
        heartText.setInputVerifier(integerVerifier);
        pressureText.setInputVerifier(integerVerifier);
        weightText.setInputVerifier(integerVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createHospitalTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        heartLabel = new javax.swing.JLabel();
        pressureLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        createVitalsButton = new javax.swing.JButton();
        vitalsBackButton = new javax.swing.JButton();
        respiratoryText = new javax.swing.JTextField();
        heartText = new javax.swing.JTextField();
        pressureText = new javax.swing.JTextField();
        weightText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        createHospitalTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        createHospitalTitle.setText("CREATE VITAL SIGNS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Respiratory Rate :");

        heartLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        heartLabel.setText("Heart Rate :");

        pressureLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pressureLabel.setText("Body Pressure :");

        weightLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        weightLabel.setText("Weight(In Pounds):");

        createVitalsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createVitalsButton.setText("CREATE");
        createVitalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVitalsButtonActionPerformed(evt);
            }
        });

        vitalsBackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vitalsBackButton.setText("<<Back");
        vitalsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalsBackButtonActionPerformed(evt);
            }
        });

        respiratoryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respiratoryTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(createHospitalTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(heartLabel)
                            .addComponent(pressureLabel)
                            .addComponent(weightLabel))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respiratoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heartText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pressureText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(createVitalsButton)))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(vitalsBackButton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createHospitalTitle)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(heartLabel)
                        .addGap(18, 18, 18)
                        .addComponent(pressureLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightLabel)
                            .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(respiratoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(heartText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pressureText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addComponent(createVitalsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(vitalsBackButton)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vitalsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalsBackButtonActionPerformed
        // TODO add your handling code here:
        vitalSignsRecord createPanel = new vitalSignsRecord(sp,personDirectory,patientDirectory);
        sp.setRightComponent(createPanel);
    }//GEN-LAST:event_vitalsBackButtonActionPerformed

    private void createVitalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVitalsButtonActionPerformed
        // TODO add your handling code here:
      try {
            int respiratoryRate = Integer.parseInt(respiratoryText.getText());
            int heartRate = Integer.parseInt(heartText.getText());
            int bloodPressure = Integer.parseInt(pressureText.getText());
            int weight = Integer.parseInt(weightText.getText());
            
            VitalSign vitalSign = patient.getVitalSignHistoryList().createAndAddVitalSign();
            vitalSign.setRespiratoryRate(respiratoryRate);
            vitalSign.setHeartRate(heartRate);
            vitalSign.setBloodPressure(bloodPressure);
            vitalSign.setWeight(weight);
            
            vitalSign.setTimestamp(new Date());
            JOptionPane.showMessageDialog(this, "Vital signs added!!", "Update",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
       } catch (Exception ex) {
          JOptionPane.showMessageDialog(this, "Please enter correct values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_createVitalsButtonActionPerformed

    private void respiratoryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respiratoryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respiratoryTextActionPerformed

     private void clearFields() {
        respiratoryText.setText("");
        heartText.setText("");
        pressureText.setText("");
        weightText.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createHospitalTitle;
    private javax.swing.JButton createVitalsButton;
    private javax.swing.JLabel heartLabel;
    private javax.swing.JTextField heartText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pressureLabel;
    private javax.swing.JTextField pressureText;
    private javax.swing.JTextField respiratoryText;
    private javax.swing.JButton vitalsBackButton;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightText;
    // End of variables declaration//GEN-END:variables
}
