/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Model.PatientHistory;
import UserInterface.JPanelPatientSignUpForm1;
import javax.swing.JSplitPane;

/**
 *
 * @author naman
 */
public class PatientSignInSignUp extends javax.swing.JFrame {
    PatientHistory history;

    /**
     * Creates new form PatientSignInSignUp
     */
    public PatientSignInSignUp() {
        initComponents();
        this.history=history;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneSignInSignUp = new javax.swing.JSplitPane();
        jPanelLeftPatientSignInSignUp = new javax.swing.JPanel();
        JFramePatientSignUpButton = new javax.swing.JButton();
        JFramePatientSignInButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelRightPatientSignInSignUp = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPaneSignInSignUp.setBackground(new java.awt.Color(204, 204, 255));
        jSplitPaneSignInSignUp.setBorder(null);
        jSplitPaneSignInSignUp.setDividerLocation(250);

        jPanelLeftPatientSignInSignUp.setBackground(new java.awt.Color(204, 204, 255));
        jPanelLeftPatientSignInSignUp.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 51, 255)));

        JFramePatientSignUpButton.setText("Sign Up");
        JFramePatientSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFramePatientSignUpButtonActionPerformed(evt);
            }
        });

        JFramePatientSignInButton.setText("Sign In");
        JFramePatientSignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFramePatientSignInButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftPatientSignInSignUpLayout = new javax.swing.GroupLayout(jPanelLeftPatientSignInSignUp);
        jPanelLeftPatientSignInSignUp.setLayout(jPanelLeftPatientSignInSignUpLayout);
        jPanelLeftPatientSignInSignUpLayout.setHorizontalGroup(
            jPanelLeftPatientSignInSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftPatientSignInSignUpLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanelLeftPatientSignInSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JFramePatientSignInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(JFramePatientSignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanelLeftPatientSignInSignUpLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLeftPatientSignInSignUpLayout.setVerticalGroup(
            jPanelLeftPatientSignInSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftPatientSignInSignUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(JFramePatientSignInButton)
                .addGap(53, 53, 53)
                .addComponent(JFramePatientSignUpButton)
                .addGap(436, 436, 436))
        );

        jSplitPaneSignInSignUp.setLeftComponent(jPanelLeftPatientSignInSignUp);

        jPanelRightPatientSignInSignUp.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanelRightPatientSignInSignUpLayout = new javax.swing.GroupLayout(jPanelRightPatientSignInSignUp);
        jPanelRightPatientSignInSignUp.setLayout(jPanelRightPatientSignInSignUpLayout);
        jPanelRightPatientSignInSignUpLayout.setHorizontalGroup(
            jPanelRightPatientSignInSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        jPanelRightPatientSignInSignUpLayout.setVerticalGroup(
            jPanelRightPatientSignInSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jSplitPaneSignInSignUp.setRightComponent(jPanelRightPatientSignInSignUp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSignInSignUp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneSignInSignUp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFramePatientSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFramePatientSignUpButtonActionPerformed
        //JPanelPatientRecord patientRecord = new JPanelPatientRecord();
        // jSplitPaneAdminPortal.setRightComponent(patientRecord );    
       JPanelPatientSignUpForm1 signin = new JPanelPatientSignUpForm1(history);
        jSplitPaneSignInSignUp.setRightComponent(signin);
//        
//           JPanelPatientSignUpForm patientSignUpForm = new JPanelPatientSignUpForm(history);
//          sp.setRightComponent(patientSignUpForm);
//        
// TODO add your handling code here:
    }//GEN-LAST:event_JFramePatientSignUpButtonActionPerformed

    private void JFramePatientSignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFramePatientSignInButtonActionPerformed
//        JPanelPatientRecord patientRecord = new JPanelPatientRecord(jSplitPaneSignInSignUp);
//        jSplitPaneSignInSignUp.setRightComponent(patientRecord );        // TODO add your handling code here:



    }//GEN-LAST:event_JFramePatientSignInButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 MainFrame signIn = new MainFrame();
       signIn.setVisible(true);   

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientSignInSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientSignInSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientSignInSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientSignInSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientSignInSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JFramePatientSignInButton;
    private javax.swing.JButton JFramePatientSignUpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelLeftPatientSignInSignUp;
    private javax.swing.JPanel jPanelRightPatientSignInSignUp;
    private javax.swing.JSplitPane jSplitPaneSignInSignUp;
    // End of variables declaration//GEN-END:variables
}
