/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import code.Hospital;
import code.HospitalDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Rajvi
 */
    
public class createHospital extends javax.swing.JPanel {
    
    /**
     * Creates new form createHospital
     */
    HospitalDirectory hospitalDirectory;
    JSplitPane sp;
    public createHospital(JSplitPane sp, HospitalDirectory hospitalDirectory) {
        initComponents();
        this.hospitalDirectory=hospitalDirectory;
        this.sp=sp;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createHospitalTitle = new javax.swing.JLabel();
        addHosNameLabel = new javax.swing.JLabel();
        addHosNameText = new javax.swing.JTextField();
        addHosAddressLabel = new javax.swing.JLabel();
        addHosAddressText = new javax.swing.JTextField();
        addHosCityLabel = new javax.swing.JLabel();
        addHosCityText = new javax.swing.JTextField();
        addHosPinCodeLabel = new javax.swing.JLabel();
        addHosPinCodeText = new javax.swing.JTextField();
        addHosTypeLabel = new javax.swing.JLabel();
        addHosTypeText = new javax.swing.JTextField();
        addHosButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        createHospitalTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        createHospitalTitle.setText("ADD A HOSPITAL");

        addHosNameLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addHosNameLabel.setText("Hospital Name:");

        addHosNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHosNameTextActionPerformed(evt);
            }
        });

        addHosAddressLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addHosAddressLabel.setText("Address:");

        addHosCityLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addHosCityLabel.setText("City:");

        addHosPinCodeLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addHosPinCodeLabel.setText("Pin Code:");

        addHosTypeLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addHosTypeLabel.setText("Type:");

        addHosButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addHosButton.setText("ADD");
        addHosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHosButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("<<Back  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addHosNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosPinCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addHosAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosPinCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addHosTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(createHospitalTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(addHosButton)))
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(createHospitalTitle)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHosNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addHosNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHosAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addHosAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHosCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addHosCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHosPinCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addHosPinCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHosTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addHosTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(addHosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addHosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHosButtonActionPerformed
        // TODO add your handling code here:
        String hospitalName = addHosNameText.getText();
        String hospitalAddress = addHosAddressText.getText();
        String cityName = addHosCityText.getText();
        String hospitalZipCode = addHosPinCodeText.getText();
        String type = addHosTypeText.getText();
        
       /* Hospital hospital = new Hospital();
        //System.out.println("testtt"+hospitalDirectory.getHospitalDirectory());
        if (hospitalDirectory!=null){
        hospitalDirectory.addNewHospital();}
        
        
        hospital.setHospitalName(hospitalName);
        hospital.setHospitalAddress(hospitalAddress);
        hospital.setCityName(cityName);
        hospital.setHospitalZipCode(hospitalZipCode);
        hospital.setType(type);*/
        Hospital hospital=new Hospital();
        hospital.setHospitalName(hospitalName);
        hospital.setHospitalAddress(hospitalAddress);
        hospital.setCityName(cityName);
        hospital.setHospitalZipCode(hospitalZipCode);
         hospital.setType(type);
if(hospitalDirectory != null){
	hospitalDirectory.addHospitalToList(hospital);
}
else{
	hospitalDirectory=new HospitalDirectory();
	hospitalDirectory.addHospitalToList(hospital);
}
        
        JOptionPane.showMessageDialog(this, " New Hospital Added to Records");
        System.out.println("testtt"+hospitalDirectory.getHospitalDirectory());
        
        addHosNameText.setText(null);
        addHosAddressText.setText(null);
        addHosCityText.setText(null);
        addHosPinCodeText.setText(null);
        addHosTypeText.setText(null);
    }//GEN-LAST:event_addHosButtonActionPerformed

    private void addHosNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHosNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHosNameTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hospitalRecord openPanel = new hospitalRecord(sp,hospitalDirectory);
        sp.setRightComponent(openPanel);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addHosAddressLabel;
    private javax.swing.JTextField addHosAddressText;
    private javax.swing.JButton addHosButton;
    private javax.swing.JLabel addHosCityLabel;
    private javax.swing.JTextField addHosCityText;
    private javax.swing.JLabel addHosNameLabel;
    private javax.swing.JTextField addHosNameText;
    private javax.swing.JLabel addHosPinCodeLabel;
    private javax.swing.JTextField addHosPinCodeText;
    private javax.swing.JLabel addHosTypeLabel;
    private javax.swing.JTextField addHosTypeText;
    private javax.swing.JLabel createHospitalTitle;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
