/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import AdminGUI.adminPortal;
import code.HospitalDirectory;
import javax.swing.JPanel;
import code.Hospital;
import java.awt.CardLayout;
import javax.swing.JSplitPane;
import gui.createHospital;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rajvi
 */
public class hospitalRecord extends javax.swing.JPanel {
   
    /**
     * Creates new form hospitalRecord
     */
    JSplitPane sp;
    HospitalDirectory hospitalDirectory;
    public hospitalRecord( JSplitPane sp, HospitalDirectory hospitalDirectory) {
        this.sp=sp;
        this.hospitalDirectory=hospitalDirectory;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalBackButton = new javax.swing.JButton();
        createHospitalButton = new javax.swing.JButton();
        viewHospitalButton = new javax.swing.JButton();
        updateHospitalButton = new javax.swing.JButton();
        deleteHospitalButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewHospitalTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewHospitalNameText = new javax.swing.JTextField();
        viewHospitalAddressText = new javax.swing.JTextField();
        viewHospitalCityText = new javax.swing.JTextField();
        viewHospitalPinCodeText = new javax.swing.JTextField();
        viewHospitalTypeText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        hospitalBackButton.setText("Back");
        hospitalBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalBackButtonActionPerformed(evt);
            }
        });

        createHospitalButton.setText("Create a New Records");
        createHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHospitalButtonActionPerformed(evt);
            }
        });

        viewHospitalButton.setText("View");
        viewHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHospitalButtonActionPerformed(evt);
            }
        });

        updateHospitalButton.setText("Update");
        updateHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHospitalButtonActionPerformed(evt);
            }
        });

        deleteHospitalButton.setText("Delete");
        deleteHospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHospitalButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("HOSPITAL DIRECTORY");

        viewHospitalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Address", "City", "Zip Code", "Type"
            }
        ));
        jScrollPane1.setViewportView(viewHospitalTable);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Hospital Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Hospital Address:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("City :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Hospital Zip Code:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Hospital Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hospitalBackButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createHospitalButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(viewHospitalButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateHospitalButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteHospitalButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewHospitalTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewHospitalPinCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewHospitalCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewHospitalNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(viewHospitalAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteHospitalButton)
                    .addComponent(updateHospitalButton)
                    .addComponent(viewHospitalButton)
                    .addComponent(createHospitalButton)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHospitalNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHospitalAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHospitalCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHospitalPinCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewHospitalTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(hospitalBackButton)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalBackButtonActionPerformed
        // TODO add your handling code here:
        adminPortal createPanel = new adminPortal();
        createPanel.setVisible(true);
    }//GEN-LAST:event_hospitalBackButtonActionPerformed

    private void createHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHospitalButtonActionPerformed
        // TODO add your handling code here:
        createHospital newPanel = new createHospital(sp,hospitalDirectory);
        sp.setRightComponent(newPanel);
        
    }//GEN-LAST:event_createHospitalButtonActionPerformed

    private void updateHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHospitalButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = viewHospitalTable.getSelectedRow();
        
        if (selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this,"Please Select A row to be Updated");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) viewHospitalTable.getModel();
        Hospital selectedHospital = (Hospital) model.getValueAt(selectedRowIndex, 0);
        
        model.setValueAt(viewHospitalNameText.getText(),selectedRowIndex,0);
        model.setValueAt(viewHospitalAddressText.getText(),selectedRowIndex,1);
        model.setValueAt(viewHospitalCityText.getText(),selectedRowIndex,2);
        model.setValueAt(viewHospitalPinCodeText.getText(),selectedRowIndex,3);
        model.setValueAt(viewHospitalTypeText.getText(),selectedRowIndex,4);
        
        String hospitalName = model.getValueAt(selectedRowIndex,0).toString();
        String hospitalAddress = model.getValueAt(selectedRowIndex,1).toString();
        String hospitalCity = model.getValueAt(selectedRowIndex,2).toString();
        String hospitalZipCode = model.getValueAt(selectedRowIndex,3).toString();
        String hospitalType = model.getValueAt(selectedRowIndex,4).toString();
        
        updateHospitalName(selectedHospital,hospitalName);
        updateHospitalAddress(selectedHospital,hospitalAddress);
        updateHospitalCity(selectedHospital,hospitalCity);
        updateHospitalZipCode(selectedHospital,hospitalZipCode);
        updateHospitalType(selectedHospital,hospitalType);
        
    }//GEN-LAST:event_updateHospitalButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:'
        populateHospitalTable(hospitalDirectory.getHospitalDirectory());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHospitalButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow= viewHospitalTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row from table.", 
                    "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Hospital hospital=(Hospital) viewHospitalTable.getValueAt(selectedRow, 0);
        /*Ask confirmation*/
        int flag= JOptionPane.showConfirmDialog(this, "Are you sure want to remove?",
                "Warning", JOptionPane.YES_NO_OPTION);
        if(flag==0)
        {
            hospitalDirectory.DeleteHospital(hospital);
            populateHospitalTable(hospitalDirectory.getHospitalDirectory());
        }
    }//GEN-LAST:event_deleteHospitalButtonActionPerformed

    private void viewHospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHospitalButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = viewHospitalTable.getSelectedRow();
        
        if (selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this,"There is no row present.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) viewHospitalTable.getModel();
        Hospital selectedHospital = (Hospital) model.getValueAt(selectedRowIndex, 0);
        
        viewHospitalNameText.setText(selectedHospital.getHospitalName());
        viewHospitalAddressText.setText(selectedHospital.getHospitalAddress());
        viewHospitalCityText.setText(selectedHospital.getCityName());
        viewHospitalPinCodeText.setText(selectedHospital.getHospitalZipCode());
        viewHospitalTypeText.setText(selectedHospital.getType());
        
        
    }//GEN-LAST:event_viewHospitalButtonActionPerformed
     
    private void populateHospitalTable(ArrayList<Hospital>hospitalDirectory){
    DefaultTableModel model = (DefaultTableModel) viewHospitalTable.getModel();
    model.setRowCount(0);
    if(hospitalDirectory.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No Hospital Added. Please Add Hospital"
                    , "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    for(Hospital hospital : hospitalDirectory){
    Object[] row = new Object[5];
            row[0] = hospital;
            row[1]= hospital.getHospitalAddress();
            row[2]= hospital.getCityName();
            row[3]= hospital.getHospitalZipCode();
            row[4]= hospital.getHospitalZipCode();
            model.addRow(row);
    }
    }
   /* private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) viewHospitalTable.getModel();
        model.setRowCount(0);
        
        for  (Hospital hospital : hospitalDirectory.getHospitalDirectory()){
            Object[] row = new Object[5];
            row[0] = hospital;
            row[1]= hospital.getHospitalAddress();
            row[2]= hospital.getCityName();
            row[3]= hospital.getHospitalZipCode();
            row[4]= hospital.getHospitalZipCode();
            model.addRow(row);}*/
        
            
            
     public void updateHospitalName(Hospital hospital, String hospitalName ){
        hospital.setHospitalName(hospitalName);
    }
     
     public void updateHospitalAddress(Hospital hospital, String hospitalAddress ){
        hospital.setHospitalAddress(hospitalAddress);
        
    }
     public void updateHospitalCity(Hospital hospital, String hospitalCity ){
        hospital.setCityName(hospitalCity);
    }
     public void updateHospitalZipCode(Hospital hospital, String hospitalZipCode ){
        hospital.setHospitalZipCode(hospitalZipCode);
        
    }
     public void updateHospitalType(Hospital hospital, String hospitalType ){
        hospital.setType(hospitalType);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createHospitalButton;
    private javax.swing.JButton deleteHospitalButton;
    private javax.swing.JButton hospitalBackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateHospitalButton;
    private javax.swing.JTextField viewHospitalAddressText;
    private javax.swing.JButton viewHospitalButton;
    private javax.swing.JTextField viewHospitalCityText;
    private javax.swing.JTextField viewHospitalNameText;
    private javax.swing.JTextField viewHospitalPinCodeText;
    private javax.swing.JTable viewHospitalTable;
    private javax.swing.JTextField viewHospitalTypeText;
    // End of variables declaration//GEN-END:variables
}
